# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta"
  lane :beta do
    #increment_build_number
    #sh "cd ../ && flutter build apk --build-name FluttrVer --release"
      Dir.chdir "../.." do sh("flutter", "build", "apk", "--release", "--build-name", "FluttrVer") end # Call Flutter Build
      #gradle(task: 'bundle', build_type: 'Release')
      upload_to_play_store(
        track: 'beta',
        #version_code: flutter_version()["version_code"],
        apk: '../build/app/outputs/flutter-apk/app-release.apk',
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
